### ISSUE TITLE
Library is not thread safe

### ISSUE THREAD

**Issue by gildor** [Romavic/HttpStatusCode#1]
If check implementation, you can see this:
https://github.com/Romavic/HttpStatusCode/blob/master/httpstatuscodeRomavicdosanjos/src/main/java/ao/httpstatuscode/romavicdosanjos/statusCode/SuccessfulStatusCode.kt#L9

Which means that statues share state when they retrieved, it may cause crazy bugs in multi-threading code (even simplest one)

I recommend get rid of successfulConnectionStatus completely, it doesn't have any sense to cache this status in property, before this library shouldn't be used to avoid bugs

**Comment by Romavic** [comment]
@gildor please update your package to version: **implementation 'com.github.Romavic:HttpStatusCode:1.1.1'**, check the documentation **(https://github.com/Romavic/HttpStatusCode)**... e please return feedback, saying if the bugs have been overcome ....

**Comment by gildor** [comment]
Looks fine now, thanks
